general.import = ["alacritty-colors.toml"]

[font]
size = 16.0
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }

[cursor]
style = { shape = "Beam", blinking = "Off" }

[selection]
save_to_clipboard = true

[[hints.enabled]]
regex = "(https?|ftp|file|git|ssh|mailto)://[^\\s<>\"'()\\[\\]{}|^`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse = { mods = "None", enabled = true }
binding = { key = "O", mods = "Control|Shift" }

[keyboard]
bindings = [
  { key = "U", mods = "Alt|Shift", action = "IncreaseFontSize" },
  { key = "Y", mods = "Alt|Shift", action = "DecreaseFontSize" }
]
