Section "InputClass"
    Identifier "System Mouse and Pointer Tuning"
    MatchIsPointer "on"
    Driver "libinput"
    Option "AccelSpeed" "-0.35"
    Option "AccelProfile" "adaptive"
    Option "NaturalScrolling" "false"
EndSection

Section "InputClass"
    Identifier "System Touchpad Tuning"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
    Option "AccelSpeed" "-0.20"
EndSection
